version: '3.8'

services:
  memoriva-rag:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - memoriva-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=memoriva
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - memoriva-network

volumes:
  postgres_data:

networks:
  memoriva-network:
    driver: bridge
